### ISSUE TITLE
Genome split questions

### ISSUE THREAD

**Issue by gianfilippo** [jerryji1993/DNABERT#8]
Hi,
I have a few questions related to the training sub-sequences:

1) when you split the genome, do you merge the sub-sequences fro both strategies : non-overlapping sub-sequences and randomly sampled sub-sequences ? if so, why ? did you try each of them separately first ?

2) The randomly sampled sub-sequences range from 5 to 510bp. How do you use 6-mers for the 5bp sub-sequences? 

3) how do you train the tokenizer ?

Thanks

**Comment by Zhihan1996** [comment]
Hi,

1. We merge the sub-sequences for both strategies. Actually, we do not try each of them first since it will cost a huge amount of time.

2. We sample sub-sequences range from 10 to 510bp, so it should be fine.

3. We do not train the tokenizer. Unlike the original BERT and XLNet, we do not do sub-word tokenization. Basically, for each kmer K, the vocabulary size equals to 4^K+5 (5 special tokens). Thus, there is no need to train the tokenizer

**Comment by gianfilippo** [comment]
Hi,

1. ok
2. I asked because in the paper you report 5 to 510bp
3. I realized that after I submitted the questions

Thanks
